config/routes.rb
Rails.application.routes.draw do
  get '/tweets/:id/retweets', to: 'tweets#retweets', as: 'retweets'
  resources :tweets do
    resources :likes
    member do
      post :retweet
    end
  end

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :likes
  end


  namespace :api do
    resources :news, only: [:index, :create, :destroy, :update, :show]
    resources :tweets, only: [:create]
  end

  get '/api/:date1/:date2', to: 'tweets#date', as: "date"

  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :tweets
    # validates :tweet, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes
  
  def destroy
    update_attributes(active: true) unless active
  end

  def active_for_authentication?
    super && !active
  end
end

app/controllers/api/news_controller.rb
class Api::NewsController < ApplicationController
    include ActionController::HttpAuthentication::Basic::ControllerMethods
    http_basic_authenticate_with name: "hello", password: "world"
    

    def index

        tweets = Tweet.all.order(created_at: :desc).limit(50)
        @tweets = tweets.map {|tweet| { 
            id: tweet.id, 
            content: tweet.tweet, 
            user: tweet.user_id,  
            like_count: tweet.likes.count,
            retweets: tweet.tweet_id, 
            retwitter_from: tweet.user_id
            }}
        render json: @tweets
    end
     
    private
    
    def tweet_params
        params.require(:tweet).permit(:id, :tweet, :tweet_id, :user_id, :created_at, :updated_at)
    end
end

app/controllers/api/tweets_controller.rb
class Api::TweetsController < ApplicationController
    include ActionController::HttpAuthentication::Basic::ControllerMethods
    http_basic_authenticate_with name: "hello", password: "world"

    
    def index
        
        tweets = Tweet.all.order(created_at: :desc)
        @tweets = tweets.map {|tweet| { 
            id: tweet.id, 
            content: tweet.tweet, 
            user: tweet.user_id,  
            like_count: tweet.likes.count,
            retweets: tweet.tweet_id, 
            retwitter_from: tweet.user_id
            }}
        render json: @tweets
    end
     
    def show
    end
     
    def create
        @tweet = Tweet.new(tweet_params)
    
        if @tweet.save
            render json: @tweet, status: :created
        else
            render json: @tweet.errors, status: :unprocessable_entity
        end
    end

    def update
        if @tweet.update(tweet_params)
            render json: @tweet, status: :ok
        else
            render json: @tweet.errors, status: :unprocessable_entity
        end
    end
     
    def destroy
        @tweet.destroy
        head :no_content
    end
     
    private

    def set_new
        @tweet = Tweet.find(params[:id])
    end
    
    def tweet_params
        params.require(:tweet).permit(:id, :tweet, :tweet_id, :user_id, :created_at, :updated_at)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]


    def create
        if already_liked?
            flash[:notice] = "Ya le diste like"
        else
            @tweet.likes.create(user_id: current_user.id)
        end
            redirect_to root_path(@tweet)
    end

    def destroy

        if !(already_liked?)
          flash[:notice] = "Cannot unlike"
        else
          @like.destroy
        end
        redirect_to root_path(@tweet)
    end

    def find_like
        @like = @tweet.likes.find(params[:id])
    end


    private

    def already_liked?
        Like.where(user_id: current_user.id, tweet_id:
        params[:tweet_id]).exists?
    end

    def find_post
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
 

    def sign_up_params
        params.require(:user).permit(:name, :nickname, :picture, :email, :password, :password_confirmation)
    end

    def acount_update_params
        params.require(:user).permit(:name, :nickname, :picture, :email, :password, :password_confirmation, :current_password)
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :retweet]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  # GET /tweets.json 
  def date
    @tweets = Tweet.where("created_at <= ? AND created_at >= ?", params[:date2], params[:date1])
    render json: @tweets
  end
  
  def index
    # @tweets = Tweet.order(created_at: :desc).paginate(page: params[:page], per_page: 50)
    _tweets = params[:q] ? Tweet.where("tweet like ?", "%#{ params[:q] }%") : Tweet.order(created_at: :desc)
    @tweets = _tweets.paginate(page: params[:page], per_page: 50)
    @tweet = Tweet.new

    # if params[:tweet].present?
    #   Tweet.where('tweet = ?', params[:tweet])
    # end
  end


  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @retweet = @tweet.tweets.build
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params) 

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def retweet
    tweet = current_user.tweets.new(tweet_id: @tweet.id, tweet: @tweet.tweet)
    if tweet.save
      redirect_to tweets_path
    else
      redirect_to :back, alert: "Unable to retweet"
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :tweet_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"%>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%if flash[:notice]%>
        <div class ="notification is-primary global global-notification">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="notification is-danger global global-notification">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <nav class="navbar is-info">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do%>
            <h1 class="title is-5">Twitter</h1>
          <% end %>
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>

          <div id ="navbarExample" class="navbar-menu">
            <div class="navbar-end">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'Nuevo tweet', new_tweet_path, class: "button is-info is-inverted"%>
      
                <% if user_signed_in? %>
                  
                  <p class="control">
                    <%= link_to current_user.name,  edit_user_registration_path, class: "button is-info" %>
                  </p>

                  <p>
                    <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "button is-info" %>
                  </p>

                  <% else %>

                  <p class="control">
                    <%= link_to 'Ingresar', new_user_session_path, class: "button is-info" %>
                  </p>

                  <p class="control">
                    <%= link_to 'Registrase', new_user_registration_path, class: "button is-info" %>
                  </p>

                <% end %>
              </div>
            </div>
          </div>
      </nav>


    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <nav class="navbar navbar-light bg-light justify-content-between">
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <h1 class="pt-5"> Bienvenido <%= current_user.name %> </h1>
    <article class="media box">
        <figure class="medifa-left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">
            <%= render 'tweets/form', tweet: @tweet %>
        </div>
    </article>
    <% end %>

<% @tweets.each do |tweet| %>
        <td class="text-left">
        
        </td>
   
    <div class="box">
    <article class="media">
        <div class="media-left">
        

            <%# <figure class="image is-64x64"> %>
                <%# <%= tweet.user.picture%> 
            <%# </figure> %>
        </div> 
        <div class="media-content">
            <div class="content">
                <strong>Foto: </strong>
                <small><%= tweet.user.picture %></small> <br/>
                <strong> <%= tweet.user.name %> </strong>
                <small> @<%= tweet.user.nickname %> </small> <br/>
                <p>
                    <% arr = tweet.tweet.split(' ')%>
                    <%arr.map do |word|%>
                        <% if word.include? ('#') %>
                            <a href="<%= request.path%>?utf8=✓&amp;q=%23<%=word[1..(word.size-1)]%>&amp;commit=Search"><%=word%></a>
                        <% else %>
                            <%= word %>
                        <% end %>
                    <% end %>
                </p>

                <% if tweet.tweets.present? %>
                <p>Retwiteado por:</p>
                <ul>
                <% tweet.tweets.each do |t| %>
                    <li><%= t.user.name %></li>
                <% end %>
                </ul>
                <% end %>

                <% if time_ago_in_words(tweet.created_at).include? "less" %>
                    <small><%= time_ago_in_words(tweet.created_at).sub 'less than a minute', 'Hace menos de un minuto' %></small>
                <% elsif time_ago_in_words(tweet.created_at).include? "minutes" %>
                    <small> Hace <%= time_ago_in_words(tweet.created_at).sub 'minutes', 'minutos' %></small>
                <% elsif time_ago_in_words(tweet.created_at).include? "minute" %>
                    <small> Hace <%= time_ago_in_words(tweet.created_at).sub 'minute', 'minuto' %></small>
                <% else %>
                    <small> <%= (time_ago_in_words(tweet.created_at).sub 'about', 'Hace').sub 'hours', 'horas' %></small>
                <% end %>
            
                
            </div>

            <% if user_signed_in? %>
            <nav class="level">
            
                <div class="level-left is-mobile">
                    <% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
                    
                    <% if pre_like %>
                        <%= link_to tweet_like_path(tweet, pre_like), method: :delete, class: "level-item" do %>
                        <span class="icon"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> </span>
                        <%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? '' : ''%>
                        <% end %>
                    <% else %>
                    
                    <%= link_to tweet_likes_path(tweet), method: :post, class: "level-item" do%>
                        <span class="icon"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> </span>
                        <%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? '' : ''%>
                    <% end %>
                    
                    <% end %>

                    <%= link_to retweet_tweet_path(tweet.id), method: :post, class: "level-item" do%>
                        <span class="icon"><i class="fa fa-retweet" aria-hidden="true"></i> </span>
                        <%= tweet.tweets.count %> <%= (tweet.tweets.count) == 1 ? '' : ''%>
                    <% end %>

                    <%= link_to edit_tweet_path(tweet), class: "level-item" do%>
                        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <% end %>

                    <%= link_to tweet, method: :delete, data: {confirm: "Seguro quieres eliminar el tweet?"} do%>
                        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                    <% end %>
                </div>
            </nav>
            <% end %>
        </div>
    </article>
</div>
   
<% end %>

<%= will_paginate @tweets, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Mostrar más tweets", inner_window:1, outer_window:0%>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(tweet) do |f|%>
<%= f.error_notification%>
<div class="field">
  <div class=control>
    <%= f.input :tweet, label: "Tuitea algo bro", input_html: {class: "textarea " }, wrapper: false, label_html: {class: "label"}, placeholder: "¿Qué está pasando?"%>
  </div>
</div>
<%= f.button :submit, "Twittear", class: "button is-info" %>
<% end %>

app/views/tweets/_likes.html.erb
<h1 > aqui van los likes </h1>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Profile</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong> <%= current_user.name %> </strong>
                            <small> <%= current_user.username %> </small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="headind">Tweets</p>
                        <p class="title is-6"><%= current_user_tweet.count%> </p>
                    </div>
                </div>
            </div>

            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="headind">Following</p>
                        <p class="title is-6">123</p>
                    </div>
                </div>
            </div>

            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="headind">Followers</p>
                        <p class="title is-6">465K</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/views/tweets/edit.html.erb
<div class="control">


<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="control">
<%= render 'form', tweet: @tweet %>
</div>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="box"> 
  <div class="media-content">
    <div class="content">
      <strong>Foto: </strong>
      <small><%= @tweet.user.picture %></small> <br/>
      <strong> <%= @tweet.user.name %> </strong>
      <small> @<%= @tweet.user.nickname %> </small> <br/>
      <p><%= @tweet.tweet %></p>
    </div>
  </div>
</div>

<%= render 'form', tweet: @retweet %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>